trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: |
    git remote add github https://github.com/mstretavsky/AOC.git
    git fetch github
    git merge github/main
    git push origin main
  displayName: 'Sync with GitHub'
