trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- checkout: self
- script: |
    git remote add github https://github.com/mstretavsky/AOC.git
    git fetch github
    git merge github/main
    git push origin main
  displayName: 'Sync GitHub -> Azure DevOps'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight sync
    branches:
      include:
        - main
