trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- checkout: self
- script: |
    git checkout main
    git fetch github main
    git merge github/main
    git push origin main
  displayName: 'Sync GitHub -> Azure DevOps'
